### ISSUE TITLE
No database found for locale en

### ISSUE THREAD

**Issue by modavidc** [fmontes/fmontes.com#5]
Hi, Freddy! Thank you for reading this isssue.  

I'm following the steps in the README:

`$ git clone https://github.com/fmontes/fmontes.com.git`
`$ cd fmontes.com`
`$ yarn`
`$ yarn dev`

The problem is when I try to access the web page in browser. I get this error: 

![image](https://user-images.githubusercontent.com/22900340/184953237-5ffd1d6f-a20b-44b7-bd4d-e2aed3265991.png)

I understand that it is a Notion exception and that I have to setup a "thing" before running it in the browser, but I don't know what it is. So far, I have not been able to solve it. 

Thanks a lot for your help.

**Comment by fmontes** [comment]
Hey @modavidc 

Duplicate this page in Notion: https://feather-lettuce-980.notion.site/Template-554fa837566c4923acd8076ab53e20d8

This page / database will be your blogs posts.

To get the ID copy and paste the url of your duplicated page which is like this: https://www.notion.so/Template-554fa837566c4923acd8076ab53e20d8

All the string after "Template-" is your id.

More info here: https://stackoverflow.com/questions/67728038/where-to-find-database-id-for-my-database-in-notion

Good luck!

**Comment by modavidc** [comment]
Thank you, @fmontes. 

I followed your steps and now it's working. 

I didn't know how to create a Database in Notion, so I had to watch a video. The video also explains how to start working with the Notion API. It was very helpful.

Here is the link: https://www.youtube.com/watch?v=Pzz36k2rt10
